/**
 * Three data sources power the site:
 *   - stores.json     — TJ's store locations (generated by scripts/scrape-stores.mjs)
 *   - catalog.json    — every TJ's bag design that exists in the world (curated)
 *   - collection.json — bags Parker actually owns (written via admin form)
 */

/* ─────────────────────────────  STORES  ───────────────────────────── */

export type Store = {
  storeNumber: string
  name: string
  streetAddress: string | null
  city: string | null
  state: string
  zip: string | null
  phone: string | null
  url: string
}

/* ─────────────────────────────  CATALOG  ──────────────────────────── */

export type BagType = 'state' | 'special' | 'seasonal' | 'standard'

export type CatalogBag = {
  id: string
  name: string
  type: BagType

  /** US state name, e.g. "California". Only for type === 'state'. */
  state?: string
  /** Two-letter state code, e.g. "CA". Only for type === 'state'. */
  stateCode?: string
  /**
   * Sub-state locale when the bag isn't statewide — a region ("Northern
   * California") or city ("Brooklyn"). Used to disambiguate when a state
   * has multiple bag designs.
   */
  region?: string

  /** Release year, when known. */
  year?: number

  /** A short blurb describing the design. */
  description?: string

  /** Path to a reference photo of the bag (under public/). */
  referencePhoto?: string

  /**
   * Paths to multiple reference photos when we have more than one angle.
   * Files use the same basename convention as collection photos so the
   * angle viewer can read them: front.{ext}, back.{ext}, etc.
   */
  referencePhotos?: string[]

  /** Where the reference photo came from — credit / link back. */
  source?: string
}

/* ──────────────────────────  PARKER'S COLLECTION  ─────────────────── */

export type CollectionBag = {
  /** URL slug used in /bags/:slug routes. */
  slug: string

  /**
   * Links this bag to a CatalogBag.id. Optional — Parker can log a bag
   * that isn't in the catalog yet (we'll add it later).
   */
  catalogId?: string

  /** Override display name when catalog link is missing or wrong. */
  name?: string

  /** storeNumber from stores.json. */
  storeNumber: string

  /** ISO date string, e.g. "2024-10-12". Day-precision is fine. */
  dateAcquired: string

  /** Parker's story about this bag. Free-form prose. */
  memory: string

  /** Paths under public/ to photos Parker uploaded. First is the hero shot. */
  photos: string[]

  /** Optional photo of Parker holding/using the bag. */
  parkerPhoto?: string
}

/* ──────────────────────────  PROGRESS HELPERS  ────────────────────── */

export type ProgressStats = {
  totalBags: number
  statesCollected: number
  totalStates: number
  specialsCollected: number
  totalSpecials: number
}
