/**
 * Three data sources power the site:
 *   - stores.json     — TJ's store locations (generated by scripts/scrape-stores.mjs)
 *   - encyclopedia.json    — every TJ's bag design that exists in the world (curated)
 *   - pantry.json — bags Parker actually owns (written via admin form)
 */

/* ─────────────────────────────  STORES  ───────────────────────────── */

export type Store = {
  storeNumber: string
  name: string
  streetAddress: string | null
  city: string | null
  state: string
  zip: string | null
  phone: string | null
  url: string
}

/* ─────────────────────────────  ENCYCLOPEDIA  ──────────────────────────── */

export type BagType = 'state' | 'special' | 'standard'

export type Material =
  | 'canvas'
  | 'polypropylene'
  | 'jute'
  | 'paper'
  | 'insulated'
  | 'nylon'

export type EncyclopediaBag = {
  id: string
  name: string
  type: BagType

  /** US state name, e.g. "California". Only for type === 'state'. */
  state?: string
  /** Two-letter state code, e.g. "CA". Only for type === 'state'. */
  stateCode?: string
  /**
   * Sub-state locale when the bag isn't statewide — a region ("Northern
   * California") or city ("Brooklyn"). Used to disambiguate when a state
   * has multiple bag designs.
   */
  region?: string

  /** Release year, when known. */
  year?: number

  /** A short blurb describing the design. */
  description?: string

  /**
   * Editorial callout shown above the metadata on the detail page —
   * for rare/discontinued bags, controversy notes, or other trivia
   * worth flagging separately from the regular design blurb.
   */
  note?: string

  /**
   * Optional URLs backing up the `note` (e.g. Reddit threads, articles).
   * Rendered as a list of "More context ↗" links under the note callout.
   */
  noteSources?: string[]

  /** Path to a reference photo of the bag (under public/). */
  referencePhoto?: string

  /**
   * Paths to multiple reference photos when we have more than one angle.
   * Files use the same basename convention as pantry photos so the
   * angle viewer can read them: front.{ext}, back.{ext}, etc.
   */
  referencePhotos?: string[]

  /** Where the reference photo came from — credit / link back. */
  source?: string

  /**
   * Per-angle source URLs (e.g. the specific Poshmark listing each angle was
   * pulled from). Populated by the picker when bags are finalized; falls back
   * to `source` when an angle isn't listed here. Optional — older entries
   * keyed by a single `source` URL only have that field.
   */
  referencePhotoSources?: Partial<
    Record<'front' | 'back' | 'left' | 'right' | 'bottom', string>
  >

  /**
   * Materials the bag is made from. Most TJ totes are one material;
   * insulated coolers often have a polypropylene shell + insulated liner,
   * so this is an array. Order doesn't carry meaning.
   */
  materials?: Material[]

  /**
   * Optional CSS scale multiplier applied to the front/back photo in the
   * encyclopedia gallery card (only). Useful when a bag's design reads small
   * inside the 4:5 card frame. 1 = no zoom; 1.2 = 20% larger; edges get
   * clipped by the card's overflow-hidden. Does not affect detail-page.
   */
  cardZoom?: number

  /**
   * Colorways / seasonal prints of the same underlying bag design. When set,
   * the detail page renders a variant picker and reads photos from the
   * active variant; the entry-level referencePhotos/referencePhotoSources/
   * source are treated as fallbacks for variants that don't have their own.
   */
  variants?: EncyclopediaVariant[]
}

export type EncyclopediaVariant = {
  /** Stable slug within this entry, e.g. "classic", "halloween-2024", "pastel". */
  id: string
  /** Display label shown on the picker, e.g. "Halloween 2024". */
  name: string
  /** Release year for this specific variant, when known. */
  year?: number
  /** Short blurb just for this variant. */
  description?: string
  /** Same shape as the entry-level field. */
  referencePhotos?: string[]
  /** Same shape as the entry-level field. */
  referencePhotoSources?: Partial<
    Record<'front' | 'back' | 'left' | 'right' | 'bottom', string>
  >
  /** Reference URL specific to this variant. */
  source?: string
  /**
   * Colorways within a single variant (e.g. the four colors in the Spring
   * 2026 Mini Canvas Tote pastel capsule). When present, the detail page
   * renders a colorway carousel under the photo viewer and the active
   * colorway's photo replaces the angle-driven photo grid.
   */
  colorways?: VariantColorway[]
}

export type VariantColorway = {
  /** Stable slug within the variant, e.g. "pink". */
  id: string
  /** Display label, e.g. "Pink", "Mint Green". */
  name: string
  /** Path to this colorway's photo. */
  photo: string
  /** Optional reference listing URL for this specific photo. */
  photoSource?: string
}

/* ──────────────────────────  PARKER'S COLLECTION  ─────────────────── */

export type PantryBag = {
  /** URL slug used in /bags/:slug routes. */
  slug: string

  /**
   * Links this bag to a EncyclopediaBag.id. Optional — Parker can log a bag
   * that isn't in the encyclopedia yet (we'll add it later).
   */
  encyclopediaId?: string

  /** Override display name when encyclopedia link is missing or wrong. */
  name?: string

  /** storeNumber from stores.json. */
  storeNumber: string

  /** ISO date string, e.g. "2024-10-12". Day-precision is fine. */
  dateAcquired: string

  /** Parker's story about this bag. Free-form prose. */
  memory: string

  /** Paths under public/ to photos Parker uploaded. First is the hero shot. */
  photos: string[]
}

/* ──────────────────────────  PROGRESS HELPERS  ────────────────────── */

export type CategoryProgress = { collected: number; total: number }

export type ProgressStats = {
  totalBags: number
  byType: Record<BagType, CategoryProgress>
}

/* ──────────────────────────  CATEGORY VISIBILITY  ──────────────────
   Admin toggle for which bag categories appear on the public encyclopedia,
   the Pantry stats row, and the Log-a-Bag picker. One boolean per BagType.
   Stored in public/data/visibility.json. */

export type CategoryVisibility = {
  state: boolean
  special: boolean
  standard: boolean
}

export const DEFAULT_VISIBILITY: CategoryVisibility = {
  state: true,
  special: true,
  standard: true,
}
